# Generated by Django 5.1.1 on 2024-09-06 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'assets',
                'constraints': [models.UniqueConstraint(fields=('asset_name',), name='unique_asset_name')],
            },
        ),
        migrations.CreateModel(
            name='AssetInitials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_id', models.PositiveIntegerField()),
                ('initial_quantity', models.DecimalField(decimal_places=8, max_digits=32)),
                ('initial_weight', models.DecimalField(decimal_places=4, max_digits=6)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asset')),
            ],
            options={
                'db_table': 'asset_initials',
                'constraints': [models.UniqueConstraint(fields=('asset', 'portfolio_id'), name='unique_asset_portfolio_id')],
            },
        ),
        migrations.CreateModel(
            name='AssetPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=8, max_digits=32)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asset')),
            ],
            options={
                'db_table': 'asset_prices',
                'constraints': [models.UniqueConstraint(fields=('asset', 'date'), name='unique_asset_date')],
            },
        ),
    ]
